language: python
os:
  - linux
services:
  - docker
env:
  - PYTHON_VERSION=2
  - PYTHON_VERSION=3
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libbluetooth-dev libboost-python-dev libboost-thread-dev libglib2.0-dev python-dev build-essential
install:
  - docker build -t pygattlib -f .travis.Dockerfile --build-arg PYTHON_VERSION=$PYTHON_VERSION .
script:
  - docker run --rm pygattlib